name: Code Freeze
on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]
jobs:
  check-freeze:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code-freeze branch
        uses: actions/checkout@v2
        with:
          ref: code-freeze
      - name: Get last commit meesage
        run: echo "${{toJSON(github.event)}}"
      - name: Execute freeze
        if: github.event.head_commit.message == '@code-freeze-start'
        run: exit 1
