name: Code Freeze GitHub Action
on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]
jobs:
  code-freeze:
    runs-on: jdk11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: code-freeze
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "Last commit message ${{ github.event.head_commit.message }}."
      - run: echo "This job's status is ${{ job.status }}."