name: Code Freeze GitHub Action
on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]
jobs:
  code-freeze:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code-freeze branch
        uses: actions/checkout@v2
        with:
          ref: code-freeze
      - name: Execute freeze
        uses: actions/github-script@v6
        with:
          script: console.log(github.event.head_commit.message)